FROM node:22-alpine AS build

# Set working directory
WORKDIR /usr/src/app


COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

COPY  pnpm-lock.yaml ./pnpm-lock.yaml
COPY pnpm-workspace.yaml ./pnpm-workspace.yaml

COPY ./apps/web ./apps/web
COPY ./packages ./packages
COPY ./turbo.json ./turbo.json


# Install dependencies
RUN pnpm install

RUN npm run build

EXPOSE 3000

#CMD
CMD ["pnpm","run","start"]
